ALTER TABLE IF EXISTS "accounts" DROP CONSTRAINT IF EXISTS "owner_currency_key" CASCADE;

ALTER TABLE IF EXISTS "accounts" DROP CONSTRAINT IF EXISTS "account_owner_fkey" CASCADE;

DROP TABLE IF EXISTS "users" CASCADE;